### ISSUE TITLE
LV2 plugins cannot load external files in Carla for Windows

### ISSUE THREAD

**Issue by Lowclock** [lsp-plugins/lsp-plugins#386]
GNU Make 4.4
MinGW-W64 8.1.0
PHP 8.3.3
Carla 2.5.8
LSP 1.2.15
Windows 10 Pro, Ryzen 3700x

LV2 plugins compiled on Windows are discovered and work wonderfully, except for things like Impulse Response/Reverb that crash Carla when a file is loaded with no output in the console. The Linux versions work on the Linux version of Carla, so I'm not sure if this is a Carla or an LSP problem. Sorry for making so many issues lately. I just love your plugins on Linux and it would be great to be able to use them on Windows as well.

**Comment by sadko4u** [comment]
Need to try

**Comment by sadko4u** [comment]
Can not confirm. Just loaded an audio file in the Impulse Responses plugin:
![изображение](https://github.com/lsp-plugins/lsp-plugins/assets/12834464/1771fab4-1bd5-4407-8ff8-7613416987ec)

Need more information about the problem.
Is your file a regular .WAV file?

**Comment by sadko4u** [comment]
Even Drag&Drop works well for Carla.

**Comment by sadko4u** [comment]
Same for 64-bit windows 8.1:
![изображение](https://github.com/lsp-plugins/lsp-plugins/assets/12834464/c5191ac1-2f5f-46f4-baad-d7b1f36eadbd)

Works fine in Carla 2.5.8

**Comment by Lowclock** [comment]
> Need more information about the problem.
Is your file a regular .WAV file?

I think the IR might have SOMETHING to do with it. I have a bunch of responses that work fine on the Linux version of Impulse Responses, but on the Windows version it shows a nonsense duration,

[This is what the Windows version says.](https://imgur.com/nl5DAn4) The Linux version says the correct 0.085 s.

In Audacity, it just never gets loaded. In Carla, the host or bridge crashes with nothing in the console.

[Here's the impulse.](https://github.com/lsp-plugins/lsp-plugins/files/14538526/impulse.zip)

**Comment by sadko4u** [comment]
It seems that the IR file is someway parsed improperly. I think I need to test your audio file.

**Comment by sadko4u** [comment]
Yes, can confirm that your IR file was not properly loaded.
The reason is that there was missinc `fact` chunk in the WAV file (which reports the actual number of audio frames) and the algorithm that reads RIFF file format (which has different implementation for Windows and uses MMIO instead of libsndfile on Linux/FreeBSD) didn't properly handle this case.
Now fix is committed into `devel` branch.

**Comment by Lowclock** [comment]
Well I'm glad it was something easy to figure out! That response was exported directly from Room EQ Wizard. I'm not sure why the author would leave that out if it's something common or expected, but if you can work around it then I guess it doesn't matter a whole lot. I'll give that branch some time soon. Thanks!

**Comment by Lowclock** [comment]
Or at least mostly, haha. It works until you try to do something like save or reload the Carla profile, where it replaces the IR with a big red "PERMISSION DENIED", presumably because of this.

> [carla] File::createSymbolicLink failed, unsupported

If I manually copy the IR to where it tries to symlink it then works as it should. Is this a Carla issue or LSP?

**Comment by sadko4u** [comment]
LSP uses standard [mapPath](https://lv2plug.in/ns/ext/state#mapPath) feature of LV2 specification when saving and restoring plugin state. The use of this function is required as it allows to copy the desired file to the project to make it portable between computers. It seems that Carla is not properly dealing with this function.

Look at the related issues: (one)[https://github.com/lsp-plugins/lsp-plugins/issues/119], (two)[https://github.com/lsp-plugins/lsp-plugins/issues/118], (three)[https://github.com/lsp-plugins/lsp-plugins/issues/132]

Especially I think that using symlinks to implement this feature is a completely bad idea because it breaks portability to Windows where symlinks are great pain.

@falkTX any comments about this?

**Comment by falkTX** [comment]
carla (and any host) should handle the case of systems where symlinks are not supported and directly copy the file instead.
so I would classify this as a host bug. never seen before because:
1. I rarely use windows, only go there to test if my tools work
2. even more rarely is using LV2 plugins under windows
3. didnt expect people to take the case of carla + lv2 plugins on windows seriously

but now there is a valid usecase here. the fix should be pretty simple, detect symlink fail and use a copy instead.
carla already does it in a few places, so there is just one or 2 where this needs to be put in place too.

**Comment by sadko4u** [comment]
@Lowclock is the IR file provided by you someway copyrighted?
I want to add it to the source tree for using in unit tests.

**Comment by Lowclock** [comment]
@sadko4u 
> @Lowclock is the IR file provided by you someway copyrighted? I want to add it to the source tree for using in unit tests.

I'm no copyright expert, but I made it with Room EQ Wizard with my own measurement, so I assume there's nothing wrong with that. I certainly don't mind.

@falkTX 
> didnt expect people to take the case of carla + lv2 plugins on windows seriously

To be fair, I don't think anyone else does either, but I can't use the VST3s yet so I'll take what I can get!

I just want to use the best plugins with the best host :)

**Comment by sadko4u** [comment]
> I'm no copyright expert, but I made it with Room EQ Wizard with my own measurement, so I assume there's nothing wrong with that. I certainly don't mind.

@Lowclock So actually I need your approval to add the impulse to the source code tree.

**Comment by Lowclock** [comment]
> @Lowclock So actually I need your approval to add the impulse to the source code tree.

Yeah, sure, go ahead.

**Comment by sadko4u** [comment]
Fixed in 1.2.16!
