### ISSUE TITLE
Add x11 as Requirement in README

### ISSUE THREAD

**Issue by gluethegiant** [lsp-plugins/lsp-plugins#401]
It should be more clear that the plugins are generally not stable under Wayland. For example, I haven't been able to use LSP for a long time, but I just recently learned that Wayland has the problem.
 
With more distros using Wayland as a default compositor, and with Wayland becoming more popular, it would make sense to note on the README Requirements that LSP is currently unstable on Wayland and needs x11.

**Comment by sadko4u** [comment]
The key problem here is that CLAP is the only plugin format that supports Wayland window handles. All other plugin formats support X11 only at this moment.
Maybe it is a good reason for @drobilla to add Wayland support to LV2 standard specification.

**Comment by sadko4u** [comment]
Added Wayland and XWayland section to README.md:
https://github.com/lsp-plugins/lsp-plugins/blob/devel/README.md#wayland-and-xwayland

**Comment by sadko4u** [comment]
@mrusme for which purposes do you install EasyEffects on your system then?

**Comment by mrusme** [comment]
@sadko4u I'm solely looking for a way to be able to alter microphone input, mainly in pitch, but ideally with other things like echo/reverb.

**Comment by sadko4u** [comment]
LSP Plugins use x11 for UI rendering but LV2 and LADSPA plugin formats actually don't strictly require x11 because LV2 allows to run plugins without UI (as LV2 UI is placed in a separate shared object file) and LADSPA also does not have any UI at all. JACK versions of LSP plugins allow to run in headless mode but use dynamic linking with xlib.

So it really depends on package maintainers how the requirements of the package are set in package build.

You can try to use GStreamer + LADSPA or GStreamer + LV2 without EasyEffects. LSP Plugins also will provide basic support of GStreamer in upcoming release.

**Comment by sadko4u** [comment]
Available in 1.2.17.
