### ISSUE TITLE
FR: 6+ Channel Compressor (Surround Compressor)

### ISSUE THREAD

**Issue by pallaswept** [lsp-plugins/lsp-plugins#405]
Hi Sadko4u :)

I have noticed that there are no surround-sound capable compressors for linux. Since I really like LSP, and I notice that your plugins are well-maintained, I started to wonder if maybe you could help us?

Thanks!

**Comment by sadko4u** [comment]
Hello! The main problem to solve here, is how to support variable number of audio channels and compressor (and other) devices. Many plugin formats allow to define only the fixed number of audio inputs and outputs, so we can define only the maximum possible number of channels. If we define 12 channels per device, then if you want to mix 5.1 audio, you'll utilize only 6 of them.

Additionally, this will yield to additional devices in plugin bundles and we're thinking at this moment about how to reduce the number of devices and get rid of separate Sidechain and Left/Right, Mid/Side versions while keeping backward compatibility.

If you have suggestions or references about how to design the proper solutions, you're welcome.

**Comment by LebedevRI** [comment]
Wouldn't it be sufficient to just have a standalone Compressor Mono instance per each channel,
and feed them all with the same pre-processed Sidechain?
The latter, however, seems like the missing piece - what would be the sidechain in that case?
It isn't necessarily a sum of all channels, since "MAX" of all channels should be default. (#274)

**Comment by pallaswept** [comment]
> we're thinking at this moment about how to reduce the number of devices

Oops! I paused to consider this, and suddenly it has been a month already! Where does the time go?!

Honestly, I was starting to give up, thinking that maybe my request is just too much 'bloat', and maybe the task of providing surround plugins is something best left to a plugin suite dedicated exclusively to that task.

But this: 
> have a standalone Compressor Mono instance per each channel, and feed them all with the same pre-processed Sidechain?

Seems like a really good and simple idea, so maybe there is more hope for this FR?

I do know that I could implement exactly this design, by chaining and modulating plugins appropriately, if I am using a DAW or modular synth or similar - but one of my use-cases for this plugin would be as an 'AVL' type limiter for playback of surround content, with the plugin hosted by pipewire. I have a friend who had similar ideas, but wanted to load the plugin into easyeffects. Pipewire could theoretically handle the submixing, routing to input and sidechain, separate plugin per channel, etc, but it is very fiddly to setup (all text config files) and I don't think easyeffects can do such things at all... So, in those contexts, it would be hard to make such a solution, without a singular plugin to do the job.

**Comment by pallaswept** [comment]
> we're thinking at this moment about how to reduce the number of devices

Oops, my bad! I paused to consider this, and suddenly it has been a month already! Where does the time go?!

Honestly, I was starting to give up, thinking that maybe my request is just too much 'bloat', and maybe the task of providing surround plugins is something best left to a plugin/suite dedicated exclusively to that task.

But this: 
> have a standalone Compressor Mono instance per each channel, and feed them all with the same pre-processed Sidechain?

Seems like a really good and simple idea, so maybe there is more hope for this FR?

I do know that I could implement exactly this design, by chaining and modulating plugins appropriately, if I am using a DAW or modular synth or similar - but one of my use-cases for this plugin would be as an 'AVL' type limiter for playback of surround content, with the plugin hosted by pipewire. I have a friend who had similar ideas, but wanted to load the plugin into easyeffects. Pipewire could theoretically handle the submixing, routing to input and sidechain, separate plugin per channel, etc, but it is very fiddly to setup (all text config files) and I don't think easyeffects can do such things at all... So, in those contexts, it would be hard to make such a solution, without a singular plugin to do the job.

**Comment by LebedevRI** [comment]
> with the plugin hosted by pipewire.

That is as achievable as doing it in DAW, see https://docs.pipewire.org/page_module_filter_chain.html
E.g. here's a working config that i use to have a limiter right before DAC: [20-master-limiter.conf.txt](https://github.com/user-attachments/files/16488508/20-master-limiter.conf.txt)

As i've said, i'm mainly not sure how to produce the appropriate sidechain,
you'd essentially need a variant of LSP Mixer, but with the mixing behavior being configurable,
instead of 'sum' being the only choice, it should support all of the possible operations
a normal sidechain supports (RMS, Peak, SMA, max, min, LPF)
@sadko4u does that sound like a reasonable improvement?

That being said, this approach results in CPU bloat, since you'll be re-computing the compressor params
in each Compressor instance, even though they will all be the same due to the sidechain being the same.
So in an ideal world LSP really should just provide even more variants of Compressor :)

**Comment by pallaswept** [comment]
You are very intuitively striking deeper into my reasoning for filing this FR :)

I use a lot of LV2 and LADSPA and native pipewire plugins in my pipewire config too. I'm a big fan of the native SOFA plugin for virtual surround when I need headphones. When I came to needing one for this role (surround compressor) I found none. 

I have read about how pipewire's filter chain could be used to route the input into another node, process it (mix channels, output max) and return it to another input of the plugin (sidechain in). Effectively it can be as powerful as a modular synth. This was (and at present, still is) my only idea how I could do this, so I had hope for it. But to be understated, it's kinda hard to set that up. In a daw I can do it by drag'n'dropping things around and it would take seconds, and be sure to work... but pipewire would need a pretty elaborate config file for this.

I have found the pipewire config to be easy to get wrong, and hard to debug. This is not intended as a criticism at all, I think pipewire is astonishing, just, my use-case is demanding and like most users I am under-skilled for it. Having it host a single plugin or a single chain of them, is one thing, but when the filter-chain begins to resemble a filter-web, I'll surely make a syntax error or 20 :smile: 

If the sidechaining you propose is done within the plugin, as it is with stereo plugins, then such a plugin could be loaded like the one you linked above, which is relatively simple.

I really like the detailed features of the sidechain processing you suggested. I would not have asked for such a complete feature set, but it would be amazing. But again I can see how it might become bloat for this project, and I don't want to cause problems, so, there is no pressure from me :)

Apologies for my double-post just now, the page glitched out after a restart and I thought I hadn't posted it. Just github trolling us :(

**Comment by sadko4u** [comment]
> That being said, this approach results in CPU bloat, since you'll be re-computing the compressor params
in each Compressor instance, even though they will all be the same due to the sidechain being the same.
So in an ideal world LSP really should just provide even more variants of Compressor :)

I'm not sure that thay can even be same.
For example, you mighty want try to compress the front group in one manner and the rear group in another manner to reach better psychoacoustic effects.

At a first glance, it all looks like N separate compressors (1 per each channel) which may be somehow linked together (for example, channels 0 and 1 for front stereo).
This is not trivial solution to make it all work and, maybe, processing separate groups with separate mono or stereo chains/busses could be a better solution.

Also, introducing such compressor requires also to introduce all other dynamic multiband and single-band plugins in the same manner.

**Comment by LebedevRI** [comment]
> > That being said, this approach results in CPU bloat, since you'll be re-computing the compressor params
> > in each Compressor instance, even though they will all be the same due to the sidechain being the same.
> > So in an ideal world LSP really should just provide even more variants of Compressor :)
> 
> I'm not sure that thay can even be same. For example, you might want try to compress the front group in one manner and the rear group in another manner to reach better psychoacoustic effects.

Sure, but there i was specifically talking about compressing all of the channels
by the same sidechain (which would be produced by the LSP Mixer taking the 'MAX' of all the channels).

**Comment by LebedevRI** [comment]
> And what if you will decide to compress 5.1 audio with 5.1 sidechain? That will be tricky.

I'm afraid i don't know what "5.1 sidechain" is, so i can't comment.

**Comment by sadko4u** [comment]
5.1 sidechain - simple. You just feed full 5.1 track (which contains of 6 channels) into 6-channel sidechain input. How to deal with it?

**Comment by LebedevRI** [comment]
I have no idea, you just came up with that, you tell me :)
I've only mentioned the most obvious case, and proposed how it can be supported.

**Comment by sadko4u** [comment]
I think all the job can be done with combination of stereo/mono compressors. Implementing multichannel compressor may only additionally complicate already complicated plugins.

**Comment by pallaswept** [comment]
Thanks for the consideration and for your advice, and big thanks for LSP :)
