### ISSUE TITLE
Impulse Response loaders increase DSP when IR loaded

### ISSUE THREAD

**Issue by audio2000** [lsp-plugins/lsp-plugins#423]
Linux Debian based distro
GTK based Desktop Environment

Tested this out in both Ardour 8.6 & Carla
Plugin Version 1.2.16
Plugin Version 1.0.23
Tried VST2, VST3 & LV2

I noticed that when you load either Impulse Responses or Impulse Reverb plugins into an audio program they seem to not really use any DSP, but then when you D&D an IR file into them all of a sudden the DSP goes up quite a bit even at idle.
I do not have a powerful PC so that could be it but it seems like these consume a good amount of CPU power even when no audio is playing, I was wondering if this was common/expected?  Something like 8-12% DSP for one plugin at idle, which is unfortunate because I really like these plugins, other IR loaders typically do not offer the parameters that LSP does.
I don't think I ever noticed high CPU usage with other IR based plugins.

Curious if anyone else can share some info about this / anyone with similar experience.
Thank You

**Comment by sadko4u** [comment]
Do you enable IR processing? Did you raise the FFT window size?
LSP Plugins use hybrid convolution algorithm which splits impulse response into sequence of chunks each growing twice to the previous unil we reach the maximum FFT frame size.
That means, for the shortest block we use direct implementation of convolution.
This allows us to become zero latency related to the input signal. The only latency the plugin can introduce is the self latency of the impulse response.

**Comment by audio2000** [comment]
@sadko4u 
I am relatively new at some of this so I might not fully understand, but I just realized something I was unaware of.
When I load up the plugin with default settings = 0% DSP
The second I loaded an IR the DSP instantly increases 8-12%
Default settings no processing / did not change any FFT settings.
My original test of this plugin was with a large IR.

I just tried a couple of different IRs and noticed the DSP changing.
So it is based on the size of the IR file / maybe length of the IR file.
A short / small size IR the DSP goes down to 1-2% which is fine.
This is good to know but still unfortunate because if want to use a specific larger IR the plugin will end up using 8-12% for one plugin at idle which seems like a lot to sacrifice.

So does anyone know if what I am saying above is expected behavior/true.
The DSP use will be based not on the plugin itself but the size/length of the IR loaded into it?
I haven't tried any other IR plugins yet I eventually test others and see if I could confirm this.

If anyone has any other information to share please let me know.
Thank You

**Comment by sadko4u** [comment]
Hello! I'll check the code, maybe we're doing some extra non needed processing when it is not necessary.

**Comment by audio2000** [comment]
Oh thank you, as mentioned it might just be my system.
Not sure if any of the following will help

Again I noticed this in both the "Impulse Responses" and "Impulses Reverb" plugin.
I have been testing the "Impulse Reverb" a little more because I think I am going to maybe use this plugin instead of the Responses plugin.

I tried both plugins in Ardour 8.6.0
-Both IR plugins use no DSP when plugins slots are empty
-Instantly when an IR file is loaded in either plugin the DSP use can jump up but again seems to be based on length of IR / size of IR (which typically go hand and hand so not sure which one is the cause) slightly larger/longer IRs end
So a .250 length 70KB IR will make DSP go from 2% to 4%
but a 1.000 length 250KB IR will make DSP go from 2% to 8-12%
All DSP is at idle, nothing going through the plugins / nothing playing

-The Impulse Reverb plugin DSP will obviously increase if add more IRs to the other 3 slots
-Turning either of the plugins off in Ardours effect chain does nothing the DSP remains
-The Impulse Reverb plugin, not sure why yet but when I drag in an IR into File 1, it makes not only slot 0 but also slot 1 active.  Muting / De-Activating slot 1 and or 0 does not change the DSP

Hopefully some of this will be helpful.
Again could just be my machine so you do not have to go too in depth at looking into this if you are busy.
Thank you again for all your help.

**Comment by sadko4u** [comment]
I've inspected the `LSP Impulse Responses` plugin:
1. Loaded the impulse file. As expected, the DSP went up because now the DSP processing started to apply to the input signal.
2. Switched processor to use 'File 2' channels of the second file which is not loaded. The DSP load has gone.

So, the behaviour is just as expected. To apply convolution, we need to perform many FFT transforms at the same time, and that requires some CPU resources. And the number of FFT transforms depends on the impulse response length. To reduce the CPU load, you can try to raise the FFT window size as it allows to perform larger FFT transforms which may cost less on your CPU because of the O(n*log(n)) complexity of the FFT algorithm.

**Comment by audio2000** [comment]
@sadko4u 

Okay, thank you for looking into this though.
I performed the same test you mention and go the same results.
They are what I mentioned I noticed that happened with both Impulse Response & Impulse Reverb plugins.
When inserted into application they do not generate any DSP at all, but only when an IR is loaded into them, depending on the IR size, the DSP increases.
Thank you again for looking at this.

I do have a quick question, hopefully okay to ask here.
Based on your test, I noticed that you decided to test this in the Impulse Reverb plugin because you knew you could try File 2, to in essence "reset" the plugin.  You did not mention you "bypassed" the plugin to achieve this.
I know this is a programming decision made by Ardour where DSP loads are always shown with or without bypassing, but some plugins seem to be able to not use ANY DSP when bypassed and some do.  In Ardour, your plugins DO continue to use DSP when bypassed, but in Carla, they DO NOT.
Just checking if this is a possible bug, or if this is expected behavior based on each application.  But again other plugins in Ardour do seem to not use DSP when bypassed, so kind of confusing.
Have tried both LV2 & VST3 versions of your plugins with same results for both.
Sorry for this question but just wanted to verify if maybe I found a bug?
If this is not expected behavior, let me know and I can make a separate "Issue" post for this topic.
Thank You

**Comment by sadko4u** [comment]
There are two types of bypass, as you've mentioned:
- Hard bypass, when turning on bypass just makes plugin to stop any processing immediately. This is not good type of bypass as it allows clicking and popping. Consider you're processing some loud signal and it immediately disappears on the maximum peak.
- Soft bypass, when the plugin fades in or fades out the changes. It allows to smoothly cross-fade non-processed signal with processed one. And there are two types of such bypass: after cross-fading plugins stops any DSP processing or continues DSP processing as usual. Regarding to the first case, if you use a reverb and turn on bypass when the tail of reverb is playing, you'll hear nothing. Regarding to the second case, you'll hear the tail of reverb.

LSP Plugins use the last one model: they process signal even if bypass is turned on. Instead of passing processed signal, they crossfade from processed signal to unprocessed signal and back.

But here is the other side which is responsible for plugin handling, and this is host. LV2 format allows to define soft bypass, and host may support it or not. Some hosts allow the plugins to run as usual after bypass is turned on, other hosts just shut down the plugin. Some hosts (like REAPER) work in both manners: they apply soft bypass when the plugin is bypassed in the track but perform the shutdown of the plugin when the track is disabled.

So, it's not a bug, you just know how LSP plugins and the host you're using behave.

**Comment by audio2000** [comment]
Thank you for this response.
Ahh I was viewing this more to not use DSP when plugins are bypassed/not being used, was not thinking about some of the things you mentioned which are based on users manual decisions and things that could be issues if using automation for example like the reverb scenario you had mentioned.
When I saw Carla drop the DSP back down zero with LSP plugins when they were bypassed/turned off in this case and then I noticed that Ardour had a different result of still showing plugins using same amount of DSP bypassed or not I just wasn't sure if this was plugin based or application based.
Okay, thank you again for answering my questions
