### ISSUE TITLE
Label Channels in Mixer Plugins

### ISSUE THREAD

**Issue by v322v322** [lsp-plugins/lsp-plugins#433]
It would be nice to be able to label the channels in the mixer plugins. It is a bit tedious having to flip to the Carla or QJackctl patchbay view to see what each mixer input is. If you do add this, please make sure the labels get stored with the save data. It would also be good  if the plugin JACK inputs would change to match (for stereo channels, make it _channelName_-l and _channelName_-r or whatever the first letters are for the words "left" and "right" in the language it is running in)

**Comment by sadko4u** [comment]
Not clear what version of plugins you use but since version 1.2.15 it is already possible to label channels:
![изображение](https://github.com/user-attachments/assets/0afa62db-56c1-4b2a-8f05-7e5c906c52aa)

The idea with renaming audio ports is not good:
- for plugin versions: rare plugin formats allow to do this, many formats are restricted relative to the length of the name;
- for JACK it is not a good idea since other tools like DAWs may rely on the port name and this may break configuration between session store and load.

**Comment by sadko4u** [comment]
Closing this ticket as invalid because such feature already exists (except the non-portable case with JACK port renaming).
