### ISSUE TITLE
VST3 UI Scaling crash

### ISSUE THREAD

**Issue by Stazed** [lsp-plugins/lsp-plugins#435]
With version 1.2.17 changing the UI Scaling from the MENU will cause a crash in Ardour and non-mixer-xt.
Downgrading to 1.2.16 the issue does not occur. Seems to occur only with VST3 and all the plugins. I checked, Chorus, Equalizer, Sampler.

**Comment by sadko4u** [comment]
Yes, reproduced the issue

**Comment by sadko4u** [comment]
The problem here was that Ardour is too dicative relative to the size of the plugin's wrapping window. When changing the size of the window, it even doesn't ask `IPlugView::checkSizeConstraints` and seems that doesn't analyze the size of the rectangle after calling the `IPlugView::onSize`.
I did some workaround but yes, the wrapper window in Ardour works badly when the plugin initiates it's resize.
@x42 FYI.

**Comment by sadko4u** [comment]
Fixed in 1.2.18.
